"""Add vendor_type_needed to maintenance_requests

Revision ID: c830807662da
Revises: ca38d43017a1
Create Date: 2025-08-23 09:07:53.834475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c830807662da'
down_revision = 'ca38d43017a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vendor_type_needed', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.drop_column('vendor_type_needed')

    # ### end Alembic commands ###
