#!/usr/bin/env python3
"""
Basic PDF Generator
Creates simple text-based PDFs with customer data without external dependencies
"""
import os
from datetime import datetime

def create_basic_pdf_content(customer_data, form_type, signature_data=None):
    """Create basic PDF content using only standard libraries"""
    
    # Create professional text-based PDF content
    content = f"""
%PDF-1.4
1 0 obj
<<
/Type /Catalog
/Pages 2 0 R
>>
endobj

2 0 obj
<<
/Type /Pages
/Kids [3 0 R]
/Count 1
>>
endobj

3 0 obj
<<
/Type /Page
/Parent 2 0 R
/MediaBox [0 0 612 792]
/Contents 4 0 R
/Resources <<
/Font <<
/F1 5 0 R
>>
>>
>>
endobj

4 0 obj
<<
/Length {len(get_content_stream(customer_data, form_type, signature_data))}
>>
stream
{get_content_stream(customer_data, form_type, signature_data)}
endstream
endobj

5 0 obj
<<
/Type /Font
/Subtype /Type1
/BaseFont /Helvetica
>>
endobj

xref
0 6
0000000000 65535 f 
0000000009 00000 n 
0000000058 00000 n 
0000000115 00000 n 
0000000271 00000 n 
0000000380 00000 n 
trailer
<<
/Size 6
/Root 1 0 R
>>
startxref
456
%%EOF
"""
    
    return content.encode('utf-8')

def get_content_stream(customer_data, form_type, signature_data):
    """Generate PDF content stream with customer data"""
    
    # Start position
    y_position = 750
    content_lines = []
    
    # Title
    content_lines.append("BT")
    content_lines.append("/F1 16 Tf")
    content_lines.append(f"50 {y_position} Td")
    title = f"Rental Application - {form_type.replace('_', ' ').title()}"
    content_lines.append(f"({title}) Tj")
    content_lines.append("ET")
    
    y_position -= 50
    
    # Customer data
    content_lines.append("BT")
    content_lines.append("/F1 12 Tf")
    
    # Field mappings
    field_mappings = [
        ('full_name', 'Full Name'),
        ('email', 'Email Address'),
        ('phone_number', 'Phone Number'),
        ('property_address', 'Property Address'),
        ('unit_number', 'Unit Number'),
        ('property_type', 'Property Type'),
        ('rent_amount', 'Monthly Rent'),
        ('security_deposit', 'Security Deposit'),
        ('lease_start', 'Lease Start Date'),
        ('lease_end', 'Lease End Date'),
        ('monthly_income', 'Monthly Income'),
        ('employment_info', 'Employment'),
        ('emergency_contact', 'Emergency Contact'),
        ('pets', 'Pets'),
        ('additional_notes', 'Additional Notes')
    ]
    
    for field_key, field_label in field_mappings:
        value = customer_data.get(field_key, '')
        if value:
            content_lines.append(f"50 {y_position} Td")
            # Escape special characters for PDF
            safe_value = str(value).replace('(', '\\(').replace(')', '\\)')
            content_lines.append(f"({field_label}: {safe_value}) Tj")
            y_position -= 20
    
    # Signature section
    if signature_data:
        y_position -= 30
        content_lines.append(f"50 {y_position} Td")
        content_lines.append("(Electronic Signature: [Digitally Signed]) Tj")
    
    # Date
    y_position -= 30
    current_date = datetime.now().strftime('%B %d, %Y')
    content_lines.append(f"50 {y_position} Td")
    content_lines.append(f"(Date: {current_date}) Tj")
    
    # Footer
    content_lines.append(f"50 50 Td")
    content_lines.append("(Generated by Ownexa Property Management System) Tj")
    content_lines.append("ET")
    
    return "\n".join(content_lines)

def create_simple_text_document(customer_data, form_type, signature_data=None):
    """Create simple text document as fallback"""
    
    content = f"""
RENTAL APPLICATION - {form_type.upper()}
=====================================

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

CUSTOMER INFORMATION:
"""
    
    # Field mappings
    field_mappings = [
        ('full_name', 'Full Name'),
        ('email', 'Email Address'),
        ('phone_number', 'Phone Number'),
        ('property_address', 'Property Address'),
        ('unit_number', 'Unit Number'),
        ('property_type', 'Property Type'),
        ('rent_amount', 'Monthly Rent'),
        ('security_deposit', 'Security Deposit'),
        ('lease_start', 'Lease Start Date'),
        ('lease_end', 'Lease End Date'),
        ('move_in_date', 'Move-in Date'),
        ('monthly_income', 'Monthly Income'),
        ('employment_info', 'Employment Information'),
        ('emergency_contact', 'Emergency Contact'),
        ('pets', 'Pets'),
        ('additional_notes', 'Additional Notes')
    ]
    
    for field_key, field_label in field_mappings:
        value = customer_data.get(field_key, '')
        if value:
            content += f"{field_label}: {value}\n"
    
    if signature_data:
        content += "\nELECTRONIC SIGNATURE: [Digitally Signed]\n"
    
    content += f"\nDate: {datetime.now().strftime('%Y-%m-%d')}\n"
    content += "\nGenerated by Ownexa Property Management System\n"
    content += f"Template Type: {form_type}\n"
    
    return content

def detect_form_type(customer_data):
    """Simple form type detection"""
    address = customer_data.get('property_address', '').lower()
    unit_number = customer_data.get('unit_number', '').strip()
    property_type = customer_data.get('property_type', '').lower()
    
    # Apartment/Condo indicators
    apt_indicators = ['apt', 'apartment', 'unit', 'condo', 'condominium', '#']
    
    if any(indicator in address for indicator in apt_indicators):
        return 'condo_apt'
    if unit_number:
        return 'condo_apt'
    if any(term in property_type for term in ['condo', 'apartment', 'unit']):
        return 'condo_apt'
    
    return 'single_family'

def save_document(content, customer_name, form_type, is_pdf=True):
    """Save document to uploads folder"""
    # Create uploads directory
    uploads_dir = 'uploads/generated_pdfs'
    os.makedirs(uploads_dir, exist_ok=True)
    
    # Create filename
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    safe_name = "".join(c for c in customer_name if c.isalnum() or c in (' ', '-', '_')).rstrip()
    extension = '.pdf' if is_pdf else '.txt'
    filename = f"{safe_name}_{form_type}_{timestamp}{extension}"
    file_path = os.path.join(uploads_dir, filename)
    
    # Save file
    mode = 'wb' if isinstance(content, bytes) else 'w'
    with open(file_path, mode, encoding='utf-8' if mode == 'w' else None) as f:
        f.write(content)
    
    return file_path

def generate_customer_document(customer_data, signature_data=None):
    """Generate document with customer data"""
    
    # Detect form type
    form_type = detect_form_type(customer_data)
    customer_name = customer_data.get('full_name', 'Unknown Customer')
    
    print(f"👤 Customer: {customer_name}")
    print(f"📋 Form type: {form_type}")
    
    try:
        # Try to create basic PDF
        pdf_content = create_basic_pdf_content(customer_data, form_type, signature_data)
        file_path = save_document(pdf_content, customer_name, form_type, is_pdf=True)
        print(f"✅ PDF document created: {file_path}")
        return file_path, form_type, len(pdf_content)
        
    except Exception as e:
        print(f"⚠️ PDF creation failed, creating text document: {e}")
        # Fallback to text document
        text_content = create_simple_text_document(customer_data, form_type, signature_data)
        file_path = save_document(text_content, customer_name, form_type, is_pdf=False)
        print(f"✅ Text document created: {file_path}")
        return file_path, form_type, len(text_content.encode('utf-8'))

def test_basic_generator():
    """Test the basic PDF generator"""
    print("🧪 Testing Basic PDF Generator")
    print("=" * 50)
    
    # Test data for apartment
    test_data_apt = {
        'full_name': 'Maria Rodriguez',
        'email': 'maria.rodriguez@example.com',
        'phone_number': '555-0789',
        'property_address': '456 Cedar Lane, Unit 5A',
        'unit_number': '5A',
        'property_type': 'apartment',
        'rent_amount': '1750.00',
        'security_deposit': '1750.00',
        'lease_start': '2024-09-01',
        'lease_end': '2025-08-31',
        'monthly_income': '5250.00',
        'employment_info': 'Marketing Coordinator at Digital Agency',
        'emergency_contact': 'Pedro Rodriguez - 555-0790',
        'pets': 'None',
        'additional_notes': 'Looking for quiet building, excellent references'
    }
    
    # Test data for single family
    test_data_house = {
        'full_name': 'James Wilson',
        'email': 'james.wilson@example.com',
        'phone_number': '555-0456',
        'property_address': '789 Oak Street',
        'property_type': 'single family',
        'rent_amount': '2500.00',
        'security_deposit': '2500.00',
        'lease_start': '2024-10-01',
        'lease_end': '2025-09-30',
        'monthly_income': '7500.00',
        'employment_info': 'Project Manager at Construction Co.',
        'emergency_contact': 'Lisa Wilson - 555-0457',
        'pets': '2 Dogs (Buddy and Rex)',
        'additional_notes': 'Family with children, seeking yard space'
    }
    
    # Sample signature
    signature = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='
    
    print("\n🏢 Testing apartment application...")
    file1, type1, size1 = generate_customer_document(test_data_apt, signature)
    print(f"📄 Generated: {size1} bytes")
    
    print("\n🏡 Testing single family application...")
    file2, type2, size2 = generate_customer_document(test_data_house, signature)
    print(f"📄 Generated: {size2} bytes")
    
    print(f"\n✅ Basic PDF generator test completed!")
    print(f"📁 Check uploads/generated_pdfs/ for created files")

if __name__ == "__main__":
    test_basic_generator()
