version: '3.8'

services:
  # Flask Backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    ports:
      - "5001:5001"
    environment:
      - NEON_DATABASE_URL=postgresql://neondb_owner:npg_V8OySJF5njdT@ep-summer-sky-adwixnct-pooler.c-2.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
      - SECRET_KEY=ownexa-local-development-secret-key-2024
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
      - .:/app  # Mount source code for hot reloading
    networks:
      - ownexa-network
    restart: unless-stopped

  # React Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_BASE_URL=http://localhost:5001
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    networks:
      - ownexa-network
    depends_on:
      - backend
    restart: unless-stopped

networks:
  ownexa-network:
    driver: bridge

volumes:
  uploads:
  logs:
