#!/usr/bin/env python3
"""
Simple PDF Text Overlay
Creates a new PDF layer over existing templates with customer data
"""
import os
from datetime import datetime

def create_simple_pdf_overlay(customer_data, form_type, signature_data=None):
    """Create a simple PDF with customer data that can be overlaid on templates"""
    try:
        from reportlab.pdfgen import canvas
        from reportlab.lib.pagesizes import letter
        import io
        
        buffer = io.BytesIO()
        p = canvas.Canvas(buffer, pagesize=letter)
        width, height = letter
        
        # Title
        p.setFont("Helvetica-Bold", 16)
        title = f"Rental Application - {form_type.replace('_', ' ').title()}"
        p.drawString(50, height - 50, title)
        
        # Customer Information
        p.setFont("Helvetica", 12)
        y_position = height - 100
        
        # Field mappings with nice labels
        field_mappings = [
            ('full_name', 'Full Name'),
            ('email', 'Email Address'),
            ('phone_number', 'Phone Number'),
            ('property_address', 'Property Address'),
            ('unit_number', 'Unit Number'),
            ('property_type', 'Property Type'),
            ('rent_amount', 'Monthly Rent'),
            ('security_deposit', 'Security Deposit'),
            ('lease_start', 'Lease Start Date'),
            ('lease_end', 'Lease End Date'),
            ('move_in_date', 'Move-in Date'),
            ('monthly_income', 'Monthly Income'),
            ('employment_info', 'Employment'),
            ('emergency_contact', 'Emergency Contact'),
            ('pets', 'Pets'),
            ('additional_notes', 'Additional Notes')
        ]
        
        for field_key, field_label in field_mappings:
            value = customer_data.get(field_key, '')
            if value:
                p.drawString(50, y_position, f"{field_label}: {value}")
                y_position -= 25
                
                # Start new page if running out of space
                if y_position < 100:
                    p.showPage()
                    p.setFont("Helvetica", 12)
                    y_position = height - 50
        
        # Add signature section
        if signature_data:
            y_position -= 40
            p.drawString(50, y_position, "Electronic Signature:")
            y_position -= 20
            p.drawString(50, y_position, "[Digitally Signed]")
            
            # Try to add actual signature image
            try:
                import base64
                from reportlab.lib.utils import ImageReader
                
                if signature_data.startswith('data:image'):
                    signature_data = signature_data.split(',')[1]
                
                signature_bytes = base64.b64decode(signature_data)
                signature_io = io.BytesIO(signature_bytes)
                
                # Add signature image
                p.drawImage(ImageReader(signature_io), 200, y_position - 30, width=150, height=40)
            except Exception as e:
                print(f"Could not add signature image: {e}")
        
        # Add date
        y_position -= 60
        current_date = datetime.now().strftime('%B %d, %Y')
        p.drawString(50, y_position, f"Date: {current_date}")
        
        # Add footer
        p.setFont("Helvetica-Oblique", 10)
        p.drawString(50, 50, "Generated by Ownexa Property Management System")
        p.drawString(50, 35, f"Template: {form_type}")
        
        p.showPage()
        p.save()
        
        pdf_bytes = buffer.getvalue()
        buffer.close()
        
        return pdf_bytes
        
    except ImportError as e:
        print(f"ReportLab not available: {e}")
        # Create text-based version
        content = f"""
RENTAL APPLICATION - {form_type.upper()}
=====================================

Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

CUSTOMER INFORMATION:
"""
        for field, value in customer_data.items():
            if value:
                label = field.replace('_', ' ').title()
                content += f"{label}: {value}\n"
        
        if signature_data:
            content += "\nELECTRONIC SIGNATURE: [Digitally Signed]\n"
        
        content += f"\nDate: {datetime.now().strftime('%Y-%m-%d')}\n"
        content += "\nGenerated by Ownexa Property Management System\n"
        
        return content.encode('utf-8')

def detect_form_type(customer_data):
    """Simple form type detection"""
    address = customer_data.get('property_address', '').lower()
    unit_number = customer_data.get('unit_number', '').strip()
    property_type = customer_data.get('property_type', '').lower()
    
    # Apartment/Condo indicators
    apt_indicators = ['apt', 'apartment', 'unit', 'condo', 'condominium', '#']
    
    if any(indicator in address for indicator in apt_indicators):
        return 'condo_apt'
    if unit_number:
        return 'condo_apt'
    if any(term in property_type for term in ['condo', 'apartment', 'unit']):
        return 'condo_apt'
    
    return 'single_family'

def save_pdf_file(pdf_content, customer_name, form_type):
    """Save PDF to uploads folder"""
    # Create uploads directory
    uploads_dir = 'uploads/generated_pdfs'
    os.makedirs(uploads_dir, exist_ok=True)
    
    # Create filename
    timestamp = datetime.now().strftime('%Y%m%d_%H%M%S')
    safe_name = "".join(c for c in customer_name if c.isalnum() or c in (' ', '-', '_')).rstrip()
    extension = '.pdf' if isinstance(pdf_content, bytes) else '.txt'
    filename = f"{safe_name}_{form_type}_{timestamp}{extension}"
    file_path = os.path.join(uploads_dir, filename)
    
    # Save file
    mode = 'wb' if isinstance(pdf_content, bytes) else 'w'
    with open(file_path, mode) as f:
        f.write(pdf_content)
    
    return file_path

def test_simple_overlay():
    """Test the simple PDF overlay system"""
    print("🧪 Testing Simple PDF Overlay System")
    print("=" * 50)
    
    # Test data
    test_data = {
        'full_name': 'Emma Wilson',
        'email': 'emma.wilson@example.com',
        'phone_number': '555-0456',
        'property_address': '789 Oak Street, Apt 3C',
        'unit_number': '3C',
        'property_type': 'apartment',
        'rent_amount': '1400.00',
        'security_deposit': '1400.00',
        'lease_start': '2024-07-01',
        'lease_end': '2025-06-30',
        'monthly_income': '4200.00',
        'employment_info': 'Graphic Designer at Creative Studio',
        'emergency_contact': 'David Wilson - 555-0457',
        'pets': '1 Cat (Whiskers)',
        'additional_notes': 'Non-smoker, excellent references'
    }
    
    # Sample signature
    signature = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNk+M9QDwADhgGAWjR9awAAAABJRU5ErkJggg=='
    
    print(f"👤 Customer: {test_data['full_name']}")
    print(f"🏠 Property: {test_data['property_address']}")
    
    # Detect form type
    form_type = detect_form_type(test_data)
    print(f"📋 Detected form type: {form_type}")
    
    # Create PDF
    pdf_content = create_simple_pdf_overlay(test_data, form_type, signature)
    print(f"📄 Generated PDF: {len(pdf_content)} bytes")
    
    # Save PDF
    file_path = save_pdf_file(pdf_content, test_data['full_name'], form_type)
    print(f"💾 Saved to: {file_path}")
    
    print("✅ Simple PDF overlay test completed!")

if __name__ == "__main__":
    test_simple_overlay()
