"""Add vendor and maintenance request tables

Revision ID: a49b238bd758
Revises: 
Create Date: 2025-08-17 02:15:05.406922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a49b238bd758'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vendor_type', sa.String(length=50), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=True),
    sa.Column('insurance_info', sa.Text(), nullable=True),
    sa.Column('hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_vendor_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('request_title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('priority', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('estimated_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('actual_cost', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('scheduled_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('completion_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('tenant_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vendor_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('owner_notes', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'vendors', ['assigned_vendor_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_column('resolution_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('maintenance_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resolution_date', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_notes')
        batch_op.drop_column('vendor_notes')
        batch_op.drop_column('tenant_notes')
        batch_op.drop_column('completion_date')
        batch_op.drop_column('scheduled_date')
        batch_op.drop_column('actual_cost')
        batch_op.drop_column('estimated_cost')
        batch_op.drop_column('priority')
        batch_op.drop_column('request_title')
        batch_op.drop_column('assigned_vendor_id')

    op.drop_table('vendors')
    # ### end Alembic commands ###
